[project]
id = "sdl"
version = "0.9.0"
src = "src"
out = "out/{target.name}/{profile.name}"
mach = ">=6.0"

[target.linux-x86_64]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.windows]
isa = "x86_64"
os  = "windows"
abi = "win64"

[target.darwin]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[profile.debug]
opt            = 0
debug          = true
simd           = "scalarize"
vectorize      = false
float_reassoc  = false
default        = true

[profile.release]
opt            = 2
debug          = false
simd           = "scalarize"
vectorize      = false
float_reassoc  = false



[artifact.demo]
kind    = "bin"
entry   = "main.mach"
out     = "bin/demo{artifact.suffix}"
targets = ["*"]
link    = ["sdl", "sdl-win", "sdl-ttf", "sdl-ttf-win", "sdl-image", "sdl-image-win", "sdl-mixer", "sdl-mixer-win"]
need    = []

[link.sdl]
source  = "system"
name    = "SDL3"
library = "sdl"
os     = ["linux", "darwin"]
isa    = "*"
abi    = "*"
export = true

[link.sdl-win]
source  = "system"
name    = "SDL3.dll"
library = "sdl"
os     = ["windows"]
isa    = "*"
abi    = "*"
export = true

[link.sdl-ttf]
source  = "system"
name    = "SDL3_ttf"
library = "sdl-ttf"
os      = ["linux", "darwin"]
isa     = "*"
abi     = "*"
export  = true

[link.sdl-ttf-win]
source  = "system"
name    = "SDL3_ttf.dll"
library = "sdl-ttf"
os      = ["windows"]
isa     = "*"
abi     = "*"
export  = true

[link.sdl-image]
source  = "system"
name    = "SDL3_image"
library = "sdl-image"
os      = ["linux", "darwin"]
isa     = "*"
abi     = "*"
export  = true

[link.sdl-image-win]
source  = "system"
name    = "SDL3_image.dll"
library = "sdl-image"
os      = ["windows"]
isa     = "*"
abi     = "*"
export  = true

[link.sdl-mixer]
source  = "system"
name    = "SDL3_mixer"
library = "sdl-mixer"
os      = ["linux", "darwin"]
isa     = "*"
abi     = "*"
export  = true

[link.sdl-mixer-win]
source  = "system"
name    = "SDL3_mixer.dll"
library = "sdl-mixer"
os      = ["windows"]
isa     = "*"
abi     = "*"
export  = true

[dep.std]
git = "https://github.com/briar-systems/mach-std"
ref = "branch/main"
