[project]
id = "sdl"
version = "1.1.0"
src = "src"
out = "out/{target.name}/{profile.name}"
mach = "^6"

[target.linux-x86_64]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.windows]
isa = "x86_64"
os  = "windows"
abi = "win64"

[target.darwin]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[profile.debug]
opt            = 0
debug          = true
simd           = "scalarize"
vectorize      = false
float_reassoc  = false
default        = true

[profile.release]
opt            = 2
debug          = false
simd           = "scalarize"
vectorize      = false
float_reassoc  = false



# the library, and the only artifact `mach build .` selects
[artifact.sdl]
kind    = "static"
default = true
entry   = "lib/libsdl.mach"
out     = "lib/sdl"
targets = ["*"]
link    = ["sdl", "sdl-win", "sdl-darwin", "sdl-ttf", "sdl-ttf-win", "sdl-ttf-darwin", "sdl-image", "sdl-image-win", "sdl-image-darwin", "sdl-mixer", "sdl-mixer-win", "sdl-mixer-darwin"]
need    = []

[link.sdl]
source  = "system"
name    = "SDL3"
library = "sdl"
os     = ["linux"]
isa    = "*"
abi    = "*"
export = true

[link.sdl-win]
source  = "system"
name    = "SDL3.dll"
library = "sdl"
os     = ["windows"]
isa    = "*"
abi    = "*"
export = true

[link.sdl-darwin]
source  = "system"
name    = "SDL3"
library = "sdl"
os      = ["darwin"]
isa     = "*"
abi     = "*"
export  = true

[link.sdl-ttf]
source  = "system"
name    = "SDL3_ttf"
library = "sdl-ttf"
os      = ["linux"]
isa     = "*"
abi     = "*"
export  = true

[link.sdl-ttf-win]
source  = "system"
name    = "SDL3_ttf.dll"
library = "sdl-ttf"
os      = ["windows"]
isa     = "*"
abi     = "*"
export  = true

[link.sdl-ttf-darwin]
source  = "system"
name    = "SDL3_ttf"
library = "sdl-ttf"
os      = ["darwin"]
isa     = "*"
abi     = "*"
export  = true

[link.sdl-image]
source  = "system"
name    = "SDL3_image"
library = "sdl-image"
os      = ["linux"]
isa     = "*"
abi     = "*"
export  = true

[link.sdl-image-win]
source  = "system"
name    = "SDL3_image.dll"
library = "sdl-image"
os      = ["windows"]
isa     = "*"
abi     = "*"
export  = true

[link.sdl-image-darwin]
source  = "system"
name    = "SDL3_image"
library = "sdl-image"
os      = ["darwin"]
isa     = "*"
abi     = "*"
export  = true

[link.sdl-mixer]
source  = "system"
name    = "SDL3_mixer"
library = "sdl-mixer"
os      = ["linux"]
isa     = "*"
abi     = "*"
export  = true

[link.sdl-mixer-win]
source  = "system"
name    = "SDL3_mixer.dll"
library = "sdl-mixer"
os      = ["windows"]
isa     = "*"
abi     = "*"
export  = true

[link.sdl-mixer-darwin]
source  = "system"
name    = "SDL3_mixer"
library = "sdl-mixer"
os      = ["darwin"]
isa     = "*"
abi     = "*"
export  = true

[dep.std]
git = "https://github.com/briar-systems/mach-std"
ref = "branch/main"
